import type { AgentPathLayout as CanonicalAgentPathLayout } from '@agent/config/config.contract'
import {
  ensureAgentPathLayout as canonicalEnsureAgentPathLayout,
  resolveAgentPathLayout as canonicalResolveAgentPathLayout,
  resolveCurrentRelease as canonicalResolveCurrentRelease,
  resolveDataDir as canonicalResolveDataDir,
  resolveInstalledLinuxAgentPathLayout as canonicalResolveInstalledLinuxAgentPathLayout,
  resolveReleasesDir as canonicalResolveReleasesDir,
} from '@agent/config/resolve-agent-paths'
import type {
  ResolveAgentDataDirCommand as CanonicalResolveAgentDataDirCommand,
  ResolveAgentPublicStateDirCommand as CanonicalResolveAgentPublicStateDirCommand,
} from '@agent/runtime/paths'
import {
  resolveAgentConfigDir as canonicalResolveAgentConfigDir,
  resolveAgentDataDir as canonicalResolveAgentDataDir,
  resolveAgentDataDirFrom as canonicalResolveAgentDataDirFrom,
  resolveAgentPublicBackendStatePath as canonicalResolveAgentPublicBackendStatePath,
  resolveAgentPublicLogsPath as canonicalResolveAgentPublicLogsPath,
  resolveAgentPublicStateDir as canonicalResolveAgentPublicStateDir,
  resolveAgentPublicStateDirFrom as canonicalResolveAgentPublicStateDirFrom,
  resolveAgentPublicStatePath as canonicalResolveAgentPublicStatePath,
  resolveLogsDir as canonicalResolveLogsDir,
  resolveReleaseStatePath as canonicalResolveReleaseStatePath,
} from '@agent/runtime/paths'

export type AgentPathLayout = CanonicalAgentPathLayout
export const ensureAgentPathLayout = canonicalEnsureAgentPathLayout
export const resolveAgentPathLayout = canonicalResolveAgentPathLayout
export const resolveCurrentRelease = canonicalResolveCurrentRelease
export const resolveDataDir = canonicalResolveDataDir
export const resolveInstalledLinuxAgentPathLayout = canonicalResolveInstalledLinuxAgentPathLayout
export const resolveReleasesDir = canonicalResolveReleasesDir
export type ResolveAgentDataDirCommand = CanonicalResolveAgentDataDirCommand
export type ResolveAgentPublicStateDirCommand = CanonicalResolveAgentPublicStateDirCommand
export const resolveAgentConfigDir = canonicalResolveAgentConfigDir
export const resolveAgentDataDir = canonicalResolveAgentDataDir
export const resolveAgentDataDirFrom = canonicalResolveAgentDataDirFrom
export const resolveAgentPublicBackendStatePath = canonicalResolveAgentPublicBackendStatePath
export const resolveAgentPublicLogsPath = canonicalResolveAgentPublicLogsPath
export const resolveAgentPublicStateDir = canonicalResolveAgentPublicStateDir
export const resolveAgentPublicStateDirFrom = canonicalResolveAgentPublicStateDirFrom
export const resolveAgentPublicStatePath = canonicalResolveAgentPublicStatePath
export const resolveLogsDir = canonicalResolveLogsDir
export const resolveReleaseStatePath = canonicalResolveReleaseStatePath
