import { spawn } from 'node:child_process'
import fsSync from 'node:fs'
import fs from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const DEFAULT_NODE_WINDOWS_VERSION = 'v22.11.0'
const DEFAULT_WINSW_VERSION = 'v2.12.0'

const REQUIRED_RELEASE_FILES = [
  'node/node.exe',
  'app/dist/agent.js',
  'app/dist/updater.js',
  'winsw/ContainerTrackerAgent.exe',
  'winsw/ContainerTrackerAgent.xml',
  'config/config.env',
] as const

const REQUIRED_CONFIG_KEYS = [
  'BACKEND_URL',
  'TENANT_ID',
  'AGENT_TOKEN',
  'AGENT_ID',
  'INTERVAL_SEC',
  'LIMIT',
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY',
] as const

function toErrorMessage(error: unknown): string {
  if (error instanceof Error) {
    return error.message
  }

  return String(error)
}

async function pathExists(targetPath: string): Promise<boolean> {
  try {
    await fs.access(targetPath)
    return true
  } catch {
    return false
  }
}

async function ensurePathExists(targetPath: string, label: string): Promise<void> {
  if (!(await pathExists(targetPath))) {
    throw new Error(`${label} not found: ${targetPath}`)
  }
}

function resolveRepoRoot(startDir: string): string {
  let cursor = startDir

  for (;;) {
    const marker = path.join(cursor, 'tools', 'agent', 'agent.ts')
    if (fsSync.existsSync(marker)) {
      return cursor
    }

    const parent = path.dirname(cursor)
    if (parent === cursor) {
      throw new Error('Could not resolve repository root from script location')
    }
    cursor = parent
  }
}

function runCommand(command: string, args: readonly string[], cwd: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd,
      stdio: 'inherit',
      shell: false,
    })

    child.on('error', (error) => {
      reject(new Error(`failed to run "${command}": ${toErrorMessage(error)}`))
    })

    child.on('exit', (code) => {
      if (code === 0) {
        resolve()
        return
      }

      reject(new Error(`"${command}" exited with code ${code ?? 'unknown'}`))
    })
  })
}

async function downloadFile(url: string, targetPath: string): Promise<void> {
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`download failed (${response.status}) for ${url}`)
  }

  await fs.mkdir(path.dirname(targetPath), { recursive: true })
  const arrayBuffer = await response.arrayBuffer()
  const fileBuffer = Buffer.from(arrayBuffer)
  await fs.writeFile(targetPath, fileBuffer)
}

async function findExtractedNodeDirectory(extractDir: string): Promise<string> {
  const entries = await fs.readdir(extractDir, { withFileTypes: true })
  const candidate = entries.find((entry) => entry.isDirectory() && entry.name.includes('-win-x64'))
  if (!candidate) {
    throw new Error(`could not find extracted node win-x64 directory inside ${extractDir}`)
  }

  return path.join(extractDir, candidate.name)
}

async function writeAgentEntrypointShims(distDir: string): Promise<void> {
  const agentShimPath = path.join(distDir, 'agent.js')
  const updaterShimPath = path.join(distDir, 'updater.js')

  const shimBanner = '// Generated by tools/agent/build-release.ts\n'
  await fs.writeFile(agentShimPath, `${shimBanner}import './tools/agent/agent.js'\n`, 'utf8')
  await fs.writeFile(updaterShimPath, `${shimBanner}import './tools/agent/updater.js'\n`, 'utf8')
}

async function runPreflightChecks(command: {
  readonly repoRoot: string
  readonly releaseDir: string
  readonly installerFilePath: string
  readonly configTemplatePath: string
  readonly updaterSourcePath: string
}): Promise<void> {
  const errors: string[] = []

  for (const relativePath of REQUIRED_RELEASE_FILES) {
    const absolutePath = path.join(command.releaseDir, relativePath)
    if (!(await pathExists(absolutePath))) {
      errors.push(`missing required release file: ${relativePath}`)
    }
  }

  const winswXmlPath = path.join(command.releaseDir, 'winsw', 'ContainerTrackerAgent.xml')
  if (await pathExists(winswXmlPath)) {
    const xmlContent = await fs.readFile(winswXmlPath, 'utf8')
    const requiredXmlStrings = [
      'C:\\Program Files\\ContainerTrackerAgent\\node\\node.exe',
      'C:\\Program Files\\ContainerTrackerAgent\\app\\dist\\agent.js',
      'DOTENV_PATH=C:\\ProgramData\\ContainerTrackerAgent\\config.env',
    ]

    for (const value of requiredXmlStrings) {
      if (!xmlContent.includes(value)) {
        errors.push(`winsw xml missing required string: ${value}`)
      }
    }
  }

  if (await pathExists(command.installerFilePath)) {
    const installerContentRaw = await fs.readFile(command.installerFilePath, 'utf8')

    const hasX64Mode =
      installerContentRaw.includes('ArchitecturesAllowed=x64compatible') &&
      installerContentRaw.includes('ArchitecturesInstallIn64BitMode=x64compatible')
    if (!hasX64Mode) {
      errors.push('installer.iss missing x64-only setup directives')
    }

    if (
      !installerContentRaw.includes('{app}') ||
      !installerContentRaw.includes('{commonappdata}')
    ) {
      errors.push('installer.iss must reference both {app} and {commonappdata}')
    }

    const schtasksLine = installerContentRaw
      .split(/\r?\n/)
      .find((line) => line.includes('Filename: "schtasks.exe"'))

    if (schtasksLine) {
      const normalizedSchtasksLine = schtasksLine.replaceAll('""', '"')
      const hasCmdPrefix = normalizedSchtasksLine.includes('cmd /c')
      const hasNodeExecutable = normalizedSchtasksLine.includes('{app}\\node\\node.exe')
      const hasUpdaterScript = normalizedSchtasksLine.includes('{app}\\app\\dist\\updater.js')

      if (!hasCmdPrefix || !hasNodeExecutable || !hasUpdaterScript) {
        errors.push(
          'installer.iss missing expected task command: cmd /c "{app}\\node\\node.exe" "{app}\\app\\dist\\updater.js"',
        )
      }
    } else {
      errors.push('installer.iss missing schtasks creation command')
    }
  } else {
    errors.push(`installer.iss not found: ${command.installerFilePath}`)
  }

  if (await pathExists(command.configTemplatePath)) {
    const templateContent = await fs.readFile(command.configTemplatePath, 'utf8')
    if (!/^MAERSK_ENABLED=0$/m.test(templateContent)) {
      errors.push('config.env.template must contain MAERSK_ENABLED=0')
    }

    for (const key of REQUIRED_CONFIG_KEYS) {
      const pattern = new RegExp(`^${key}=`, 'm')
      if (!pattern.test(templateContent)) {
        errors.push(`config.env.template missing key: ${key}`)
      }
    }
  } else {
    errors.push(`config.env.template not found: ${command.configTemplatePath}`)
  }

  if (await pathExists(command.updaterSourcePath)) {
    const updaterSource = await fs.readFile(command.updaterSourcePath, 'utf8')
    if (!updaterSource.includes('DOTENV_PATH')) {
      errors.push('updater.ts must reference DOTENV_PATH')
    }

    const fallbackPathLiteral = 'C:\\\\ProgramData\\\\ContainerTrackerAgent\\\\config.env'
    const fallbackPathRuntime = 'C:\\ProgramData\\ContainerTrackerAgent\\config.env'
    if (
      !updaterSource.includes(fallbackPathLiteral) &&
      !updaterSource.includes(fallbackPathRuntime)
    ) {
      errors.push('updater.ts must include fallback ProgramData path')
    }
  } else {
    errors.push(`updater.ts not found: ${command.updaterSourcePath}`)
  }

  if (errors.length > 0) {
    console.error('[agent:release] preflight failed')
    for (const error of errors) {
      console.error(`  - ${error}`)
    }
    process.exit(1)
  }

  console.log('[agent:release] preflight ok')
  console.log(
    `[agent:release] release directory: ${path.relative(command.repoRoot, command.releaseDir)}`,
  )
}

async function buildRelease(): Promise<void> {
  const scriptDir = path.dirname(fileURLToPath(import.meta.url))
  const repoRoot = resolveRepoRoot(scriptDir)
  const toolsAgentDir = path.join(repoRoot, 'tools', 'agent')
  const installerDir = path.join(toolsAgentDir, 'installer')
  const distDir = path.join(toolsAgentDir, 'dist')
  const releaseDir = path.join(repoRoot, 'release')
  const releaseAppDir = path.join(releaseDir, 'app')
  const releaseAppDistDir = path.join(releaseAppDir, 'dist')
  const releaseWinswDir = path.join(releaseDir, 'winsw')
  const releaseNodeDir = path.join(releaseDir, 'node')
  const releaseConfigDir = path.join(releaseDir, 'config')
  const tempDownloadDir = path.join(releaseDir, '.downloads')

  const nodeVersion = process.env.AGENT_NODE_WINDOWS_VERSION ?? DEFAULT_NODE_WINDOWS_VERSION
  const winswVersion = process.env.AGENT_WINSW_VERSION ?? DEFAULT_WINSW_VERSION

  const compiledAgentFile = path.join(distDir, 'tools', 'agent', 'agent.js')
  const compiledUpdaterFile = path.join(distDir, 'tools', 'agent', 'updater.js')

  await ensurePathExists(compiledAgentFile, 'compiled agent')
  await ensurePathExists(compiledUpdaterFile, 'compiled updater')

  await fs.rm(releaseDir, { recursive: true, force: true })
  await fs.mkdir(releaseDir, { recursive: true })
  await fs.mkdir(tempDownloadDir, { recursive: true })
  await fs.mkdir(releaseAppDir, { recursive: true })
  await fs.mkdir(releaseWinswDir, { recursive: true })
  await fs.mkdir(releaseConfigDir, { recursive: true })

  await fs.cp(distDir, releaseAppDistDir, { recursive: true })
  await writeAgentEntrypointShims(releaseAppDistDir)

  await fs.cp(path.join(repoRoot, 'package.json'), path.join(releaseAppDir, 'package.json'))
  await fs.cp(path.join(repoRoot, 'node_modules'), path.join(releaseAppDir, 'node_modules'), {
    recursive: true,
  })

  const nodeZipName = `node-${nodeVersion}-win-x64.zip`
  const nodeZipPath = path.join(tempDownloadDir, nodeZipName)
  const nodeExtractDir = path.join(tempDownloadDir, 'node-extracted')
  const nodeDownloadUrl = `https://nodejs.org/dist/${nodeVersion}/${nodeZipName}`
  console.log(`[agent:release] downloading node runtime: ${nodeDownloadUrl}`)
  await downloadFile(nodeDownloadUrl, nodeZipPath)

  await fs.rm(nodeExtractDir, { recursive: true, force: true })
  await fs.mkdir(nodeExtractDir, { recursive: true })
  await runCommand('unzip', ['-q', '-o', nodeZipPath, '-d', nodeExtractDir], repoRoot)

  const extractedNodeDir = await findExtractedNodeDirectory(nodeExtractDir)
  await fs.cp(extractedNodeDir, releaseNodeDir, { recursive: true })

  const winswDownloadUrl = `https://github.com/winsw/winsw/releases/download/${winswVersion}/WinSW-x64.exe`
  console.log(`[agent:release] downloading winsw: ${winswDownloadUrl}`)
  await downloadFile(winswDownloadUrl, path.join(releaseWinswDir, 'ContainerTrackerAgent.exe'))

  await fs.cp(
    path.join(installerDir, 'ContainerTrackerAgent.xml'),
    path.join(releaseWinswDir, 'ContainerTrackerAgent.xml'),
  )
  await fs.cp(
    path.join(installerDir, 'config.env.template'),
    path.join(releaseConfigDir, 'config.env'),
  )

  await fs.rm(tempDownloadDir, { recursive: true, force: true })

  await runPreflightChecks({
    repoRoot,
    releaseDir,
    installerFilePath: path.join(installerDir, 'installer.iss'),
    configTemplatePath: path.join(installerDir, 'config.env.template'),
    updaterSourcePath: path.join(toolsAgentDir, 'updater.ts'),
  })
}

void buildRelease().catch((error) => {
  console.error(`[agent:release] failed: ${toErrorMessage(error)}`)
  process.exit(1)
})
