export enum ContainerStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  LOADED = 'LOADED',
  IN_TRANSIT = 'IN_TRANSIT',
  ARRIVED_AT_POD = 'ARRIVED_AT_POD',
  DISCHARGED = 'DISCHARGED',
  DELIVERED = 'DELIVERED',
}
