import z from 'zod/v4'

export const EventSourceSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('api'),
    carrier_name: z.string(),
    raw: z.any(),
  }),
  z.object({
    type: z.literal('system'),
    details: z.string().optional(),
  }),
  z.object({
    type: z.literal('manual'),
    details: z.string().optional(),
  }),
  z.object({
    type: z.literal('error'),
    details: z.string().optional(),
  }),
])

export type EventSource = z.infer<typeof EventSourceSchema>

/*
Example EventSource values:
- API source:
  {
    type: 'api',
    carrier_name: 'CarrierX',
    raw: { ... } // original payload from CarrierX
  }
- System-generated source:
  {
    type: 'system',
    details: 'This event is generated by the system based on certain conditions.'
  }
- Manual entry source:
  {
    type: 'manual'
    details: 'Entered by user John Doe on 2024-01-01.'
  }
*/
