import type { AgentControlRendererApi as CanonicalAgentControlRendererApi } from '@agent/electron/ipc'
import {
  AgentControlBackendUrlInputSchema as canonicalAgentControlBackendUrlInputSchema,
  AgentControlBlockedVersionsInputSchema as canonicalAgentControlBlockedVersionsInputSchema,
  AgentControlChannelInputSchema as canonicalAgentControlChannelInputSchema,
  AgentControlConfigPatchInputSchema as canonicalAgentControlConfigPatchInputSchema,
  agentControlIpcChannels as canonicalAgentControlIpcChannels,
  AgentControlLogsQuerySchema as canonicalAgentControlLogsQuerySchema,
  AgentControlReleaseVersionInputSchema as canonicalAgentControlReleaseVersionInputSchema,
} from '@agent/electron/ipc'

export const agentControlIpcChannels = canonicalAgentControlIpcChannels
export const AgentControlLogsQuerySchema = canonicalAgentControlLogsQuerySchema
export const AgentControlChannelInputSchema = canonicalAgentControlChannelInputSchema
export const AgentControlBlockedVersionsInputSchema =
  canonicalAgentControlBlockedVersionsInputSchema
export const AgentControlConfigPatchInputSchema = canonicalAgentControlConfigPatchInputSchema
export const AgentControlBackendUrlInputSchema = canonicalAgentControlBackendUrlInputSchema
export const AgentControlReleaseVersionInputSchema = canonicalAgentControlReleaseVersionInputSchema

export type AgentControlRendererApi = CanonicalAgentControlRendererApi
